import InformationPage from "@/components/layout/InformationPage";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "Read how Free Agent Staff collects, uses, and protects information across the platform.",
  alternates: { canonical: "/privacy" },
  openGraph: { url: "https://freeagentstaff.com/privacy" },
};

// LEGAL: Final solicitor review required before public production launch.
export default function PrivacyPage() {
  return (
    <InformationPage
      eyebrow="Privacy Policy"
      title="Your Privacy"
      description="How Freeagentstaff collects, uses, and protects information across the platform."
    >
          <p className="text-sm font-semibold uppercase tracking-[0.2em] text-[#9a6d15]">Last updated: August 2026</p>
          <div className="mt-8 space-y-7 text-sm leading-7 text-[#f7ebcf] sm:text-base">
            <section>
              <h2 className="text-lg font-bold text-[#f7ebcf]">1. About this policy</h2>
              <p className="mt-2">
                Freeagentstaff respects your privacy and is committed to handling personal information responsibly and transparently.
              </p>
              <p className="mt-2">
                This Privacy Policy explains how Freeagentstaff collects, holds, uses and discloses personal information when you use our website, create an account or interact with our services.
              </p>
              <p className="mt-2">
                Questions or concerns about this policy can be sent to <a className="font-semibold text-[#f2cc63] underline underline-offset-4" href="mailto:support@freeagentstaff.com">support@freeagentstaff.com</a>.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-[#f7ebcf]">2. Information we collect</h2>
              <p className="mt-2">
                The information we collect depends on how you use Freeagentstaff.
              </p>
              <p className="mt-2">
                For talent users, this may include your name, email address, location, professional information, employment history, skills, experience, availability, profile content and other information you choose to provide when creating or maintaining your Talent Passport.
              </p>
              <p className="mt-2">
                For employer users, this may include your name, work email address, company name, position or role, ABN and information supplied as part of employer registration and verification.
              </p>
              <p className="mt-2">
                We may also collect account and authentication information, privacy and visibility preferences, blocked-company settings, introduction requests, connections, notifications and records relating to your use of Freeagentstaff.
              </p>
              <p className="mt-2">
                We may collect technical information associated with use of the website, such as browser, device, security and diagnostic information, where this is generated by the services and infrastructure used to operate Freeagentstaff.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-[#f7ebcf]">3. How we collect information</h2>
              <p className="mt-2">
                We primarily collect personal information directly from you when you:
              </p>
              <ul className="mt-2 list-disc space-y-1 pl-5">
                <li>create or update an account;</li>
                <li>create or edit a Talent Passport;</li>
                <li>register or verify an employer account;</li>
                <li>change privacy or visibility settings;</li>
                <li>send or respond to an introduction request;</li>
                <li>create or manage a connection;</li>
                <li>contact us for support; or</li>
                <li>otherwise use Freeagentstaff.</li>
              </ul>
              <p className="mt-2">
                We may also receive information generated through our authentication, hosting, database and other technology service providers when necessary to operate and secure the platform.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-[#f7ebcf]">4. How we use information</h2>
              <p className="mt-2">
                We may use personal information to:
              </p>
              <ul className="mt-2 list-disc space-y-1 pl-5">
                <li>create and manage accounts;</li>
                <li>provide and maintain Freeagentstaff;</li>
                <li>display Talent Passports in accordance with the talent user&apos;s privacy and visibility settings;</li>
                <li>verify employer accounts;</li>
                <li>allow eligible employers to discover talent;</li>
                <li>facilitate introduction requests and connections;</li>
                <li>provide contact information to an authorised employer after a connection has been established;</li>
                <li>enforce blocking, privacy and access controls;</li>
                <li>provide in-app workflow notifications;</li>
                <li>respond to support, privacy, correction and account requests;</li>
                <li>maintain security and prevent misuse;</li>
                <li>diagnose technical problems; and</li>
                <li>comply with applicable legal obligations.</li>
              </ul>
              <p className="mt-2">
                Freeagentstaff does not currently operate an in-platform messaging service. After an authorised connection and contact handoff, communications between talent and employers generally take place outside Freeagentstaff.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-[#f7ebcf]">5. Talent profiles and visibility</h2>
              <p className="mt-2">
                Talent users control important aspects of how their Talent Passport is made available through Freeagentstaff.
              </p>
              <p className="mt-2">
                Profile visibility is subject to the privacy, publication and eligibility controls available within the platform.
              </p>
              <p className="mt-2">
                Freeagentstaff also provides blocking controls designed to prevent blocked companies from accessing a talent user&apos;s profile through employer discovery and related protected areas of the service.
              </p>
              <p className="mt-2">
                Users should review their privacy and visibility settings and ensure they reflect their preferences.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-[#f7ebcf]">6. Employer verification</h2>
              <p className="mt-2">
                Employer access to protected talent discovery and related functionality may require employer verification.
              </p>
              <p className="mt-2">
                Information supplied by employers may be used to assess eligibility to access these features.
              </p>
              <p className="mt-2">
                Verification is an access-control measure and should not be interpreted as an endorsement, recommendation or guarantee by Freeagentstaff regarding an employer.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-[#f7ebcf]">7. Introductions, connections and contact information</h2>
              <p className="mt-2">
                Freeagentstaff allows eligible employers to request introductions to talent.
              </p>
              <p className="mt-2">
                If an introduction is accepted, a connection may be created between the employer and talent user.
              </p>
              <p className="mt-2">
                A connected and otherwise authorised employer may then be able to access the talent user&apos;s contact email through the designated contact feature.
              </p>
              <p className="mt-2">
                Contact information is not intended to be made available through general talent discovery or ordinary Talent Passport views.
              </p>
              <p className="mt-2">
                Access may subsequently be restricted where the connection is revoked or relevant privacy, blocking, publication or eligibility controls prevent access.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-[#f7ebcf]">8. Notifications</h2>
              <p className="mt-2">
                Freeagentstaff may provide in-app notifications relating to activity on your account, such as introduction requests, introduction outcomes, connection changes and relevant employer-verification events.
              </p>
              <p className="mt-2">These operational notifications form part of the service.</p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-[#f7ebcf]">9. Disclosure and service providers</h2>
              <p className="mt-2">
                We may disclose or make personal information available where reasonably necessary to operate Freeagentstaff, including to technology providers that support services such as hosting, databases, authentication, security and application infrastructure.
              </p>
              <ul className="mt-2 list-disc space-y-1 pl-5">
                <li>between talent and employer users where permitted by the platform&apos;s functionality and privacy controls;</li>
                <li>where you have authorised the disclosure;</li>
                <li>where necessary to investigate misuse or protect users or the platform; or</li>
                <li>where required or authorised by law.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-lg font-bold text-[#f7ebcf]">10. Overseas processing</h2>
              <p className="mt-2">
                Some technology providers used to operate Freeagentstaff may store or process information using infrastructure located in Australia or overseas. The location of processing may vary depending on the services and infrastructure used to operate the platform.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-slate-900">11. Security</h2>
              <p className="mt-2">
                Freeagentstaff uses technical and organisational safeguards designed to protect personal information from unauthorised access, disclosure, alteration and loss.
              </p>
              <p className="mt-2">
                However, no online service or method of electronic storage can guarantee absolute security.
              </p>
              <p className="mt-2">
                Users are responsible for protecting their login credentials and should notify us if they believe their account has been compromised.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-slate-900">12. Access and correction</h2>
              <p className="mt-2">
                Users may update certain account and profile information directly through Freeagentstaff.
              </p>
              <p className="mt-2">
                If a user cannot access or correct information themselves, they may contact <a className="font-semibold text-slate-900 underline underline-offset-4" href="mailto:support@freeagentstaff.com">support@freeagentstaff.com</a> for assistance.
              </p>
              <p className="mt-2">
                Freeagentstaff may need to verify identity before processing a request involving personal information.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-slate-900">13. Account deletion and privacy requests</h2>
              <p className="mt-2">
                Users may request account deletion or deactivation by contacting <a className="font-semibold text-slate-900 underline underline-offset-4" href="mailto:support@freeagentstaff.com">support@freeagentstaff.com</a>.
              </p>
              <p className="mt-2">
                Freeagentstaff currently handles these requests through its support process rather than through an automated self-service deletion feature.
              </p>
              <p className="mt-2">
                Some information may need to be retained where reasonably necessary for security, dispute resolution, record keeping or legal obligations.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-slate-900">14. Privacy concerns</h2>
              <p className="mt-2">Privacy questions or concerns can be sent to:</p>
              <p className="mt-2 font-semibold text-slate-900">Freeagentstaff</p>
              <p className="mt-1">
                <a className="font-semibold text-slate-900 underline underline-offset-4" href="mailto:support@freeagentstaff.com">support@freeagentstaff.com</a>
              </p>
              <p className="mt-1">New South Wales, Australia</p>
            </section>

            <section>
              <h2 className="text-lg font-bold text-slate-900">15. Changes to this policy</h2>
              <p className="mt-2">
                Freeagentstaff may update this Privacy Policy when its services, information-handling practices or legal obligations change.
              </p>
              <p className="mt-2">
                The current version will be published on the Freeagentstaff website with an updated effective date.
              </p>
            </section>
          </div>
    </InformationPage>
  );
}
